.TH "TCURL" "1" "January 2016" "v4.19.1" "tcurl"
.SH "NAME"
\fBtcurl\fR \- curl for tchannel
.SH SYNOPSIS
.P
.RS 2
.nf
tcurl <service> <method> [<body>]
      [\-t | \-\-thrift | \-j | \-\-json | \-r | \-\-raw | \-\-http]
      [\-\-rate] [\-\-requests] [\-\-time] [\-\-delay]
      [\-\-timeout] [\-\-sk] [\-\-rd]
tcurl <service> \-\-health
tcurl [\-h | \-\-help | \-v | \-\-version]
.fi
.RE
.SH DESCRIPTION
.P
\fBtcurl\fP is a tool for constructing and sending requests to
.br
a tchannel service\. It supports thrift, JSON, and raw request format\.
.SH EXAMPLES
.RS 0
.IP \(bu 2
\fBtcurl \-p localhost:8080 service \-\-health\fP
.IP \(bu 2
\fBtcurl \-p localhost:8080 service endpoint \-\-raw 'message'\fP
.IP \(bu 2
\fBtcurl hyperbahn Hyperbahn::discover \-\-body '{"query":{"serviceName":"ringpop"}}' \-t \./hyperbahn\.thrift\fP
.IP \(bu 2
\fBtcurl hyperbahn Hyperbahn::discover [ \-\-query [ \-\-serviceName ringpop ] ] \-t \./hyperbahn\.thrift\fP

.RE
.SH OPTIONS
.P
\fB\-p host:port <service> <endpoint>\fP
.P
Specify the destination where the request should be sent to including the host,
.br
the port, the serviceName, and the endpoint\.  When used with \fB\-\-health\fP,
.br
endpoint is not required\.  You can specify any number of peers and TChannel
.br
will choose one for each request\.
.P
\fB\-P <peer\-file> <serviceName> <endpoint>\fP
.P
Similar to the \fB\-p\fP option\. Instead of the host:port, it takes a peer\-file that
.br
contains a list of host:port where this request can be sent to\.  TChannel will
.br
only pick one host:port to send the request to\.
.P
The peer list file must be a JSON array of host:port strings\.
.P
\fB\-\-health\fP
.P
Send a health check request to a sevice that implements the "Meta::health"
.br
health check endpoint\.  For example:
.P
.RS 2
.nf
tcurl \-p 127\.0\.0\.1:21300 serviceName \-\-heath
.fi
.RE
.P
It is the same as:
.P
.RS 2
.nf
tcurl \-p 127\.0\.0\.1:21300 serviceName Meta::health \-t meta\.thrift
.fi
.RE
.P
\fB\-2 | \-\-arg2 | \-\-head <content>\fP
.P
Specify the head (a\.k\.a\. arg2) of the request\. The content can be either a raw
.br
string or a JSON string depending on the request format\.
.P
You can also provide the headers in SHON format as a positional argument
.br
(without the \fB\-\-head\fP flag)\.
.P
.RS 2
.nf
tcurl curly Stooges::nyuck [ \-\-nyuck [ \-\-name tcurl \-\-language js ] ] \\
    \-t curly\.thrift
.fi
.RE
.P
\fB\-3 | \-\-arg3 | \-\-body <content>\fP
.P
Specify the body (a\.k\.a\. arg3) of the request\. The content can be either a raw
.br
string or a JSON string depending on the request format\.
.P
An example of a JSON string would be:
.P
.RS 2
.nf
{"query":{"serviceName":"ringpop"}}
.fi
.RE
.P
These can also be expressed in SHON (SHell Object Notation) with a positional
.br
argument (without the \fB\-\-body\fP flag)\.
.P
.RS 2
.nf
[ \-\-query [ \-\-serviceName ringpop ] ]
.fi
.RE
.P
The corresponding thrift IDL format is:
.P
.RS 2
.nf
struct DiscoveryQuery {
  1: required string serviceName
}

service Hyperbahn {
    DiscoveryResult discover(
        1: required DiscoveryQuery query
    )
}
.fi
.RE
.P
\fB\-t <thrift>\fP
.P
Used with the thrift encoding to specify the path to the thrift files\.  The
.br
thrift option value can either point to a file or a directory\.  For example:
.P
.RS 2
.nf
tcurl \-p 127\.0\.0\.1:21300 serviceName Meta::health \-t \. null
.fi
.RE
.P
The above command assumes that current folder contains the meta\.thrift IDL file\.
.P
\fB\-\-no\-strict\fP
.P
Disable the default strict mode of thrift parsing\. When strict mode is enabled,
.br
all fields must be specified as either "required" or "optional"\.
.P
\fB\-\-raw\fP
.P
Use raw format (i\.e\. plain text) for request\.
.P
\fB\-\-http <method>\fP
.P
Send an http request described in the form of tchannel\.  For example:
.P
.RS 2
.nf
tcurl \-p 127\.0\.0\.1:21300 echoServer /echo
    \-\-http=POST 'Hello World!' \-\-headers [ \-\-Accept text/plain ]
.fi
.RE
.P
\fB\-\-shard\-key <sk>\fP or \fB\-\-sk <sk>\fP
.P
Route to the worker that owns this key within a DHT\.
.P
\fB\-\-routing\-delegate\fP or \fB\-\-rd <rd>\fP
.P
Route through the delegated service\.
.P
\fB\-\-timeout <value>\fP
.P
Specify the maximum time in miniseconds this request can take until it timeout\.
.br
For example, the following command specifies a timeout value of one second:
.P
.RS 2
.nf
tcurl \-p 127\.0\.0\.1:8080 serviceName endpoint \-\-timeout 1000
.fi
.RE
.P
\fB\-\-rate <value>\fP
.P
This option is required in order to use the benchmark mode, where the same
.br
request is sent multiple times to the server\.  It specifies the number of
.br
requests sent at each batch\.  For example, the following command sends health
.br
check requests to a service at the rate of 1000, i\.e\., send 1000 requests and
.br
wait until the requests all complete before sending the next 1000\.
.P
.RS 2
.nf
tcurl \-p localhost:8080 serviceName \-\-health \-\-rate 1000
.fi
.RE
.P
\fB\-\-delay <value>\fP
.P
Specify the time in milliseconds it should delay between each batch\.  For
.br
example, the following command delays 100ms between each batch send\.
.P
.RS 2
.nf
tcurl \-p localhost:8080 serviceName \-\-health \-\-rate 1000 \-\-delay 100
.fi
.RE
.P
\fB\-\-requests <value>\fP
.P
Specify the total number of requests that can be sent in benchmark mode\. By
.br
default, there is no limit on the number of requests that can be sent\.
.P
\fB\-\-time <value>\fP
.P
Specify the time in milliseconds how long the benchmark should run\.  When no
.br
request limit is set, the default value is 30 seconds\. Otherwise, the default
.br
is unlimited\.
.P
\fB\-h\fP
.P
View abbreviated usage information\.
.P
\fB\-\-help\fP
.P
View the man page\.
.P
\fB\-v | \-\-version\fP
.P
Print the current version\.
.SH FILES
.P
TCurl can be configured with default parameters using a either /etc/tcurlrc or
.br
a \.tcurlrc in the current working directory or any of its parent directories\.
.br
The rc file may be in INI or JSON format\.
.P
.RS 2
.nf
{
    "hostlist": "/etc/ringpop/hosts\.json"
}
.fi
.RE
.P
\fBhostlist\fP is the fully qualified path of a JSON file containing an array of
.br
host:port strings\.
.SH EXIT CODES
.RS 0
.IP \(bu 2
0: for all successful requests
.IP \(bu 2
1: timeout
.IP \(bu 2
2: cancelled
.IP \(bu 2
3: busy
.IP \(bu 2
4: declined
.IP \(bu 2
5: unexpected error
.IP \(bu 2
6: bad request
.IP \(bu 2
7: network error
.IP \(bu 2
8: unhealthy (broken circuit)
.IP \(bu 2
124: unhealthy / not OK thrift response
.IP \(bu 2
125: misc tcurl / tchannel internal error
.IP \(bu 2
126: response not ok error
.IP \(bu 2
127: fatal protocol error

.RE
.SH BUGS
.P
Please report any bugs to https://github\.com/uber/tcurl
.SH LICENCE
.P
MIT Licenced
.SH SEE ALSO
.RS 0
.IP \(bu 2
TChannel: https://github\.com/uber/tchannel
.IP \(bu 2
Hyperbahn: https://github\.com/uber/hyperbahn
.IP \(bu 2
Ringpop: https://github\.com/uber/ringpop\-node
.IP \(bu 2
SHON: https://github\.com/kriskowal/shon

.RE

